# Generated by Django 2.2.2 on 2019-06-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myGroupRait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=20)),
                ('surname', models.CharField(default='none', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('ponts', models.IntegerField(default=60)),
            ],
        ),
    ]
